apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app
        imagePullPolicy: Never
        env:
        - name: MYSQL_USER
          value: MYSQL_USER
        - name: MYSQL_PASSWORD
          value: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: MYSQL_DATABASE
        - name: MYSQL_HOST
          value: "db"
        - name: MYSQL_PORT
          value: "3306"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: my-app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort
