apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: db
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          value: MYSQL_USER
        - name: MYSQL_PASSWORD
          value: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: MYSQL_DATABASE
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: app
          mountPath: /app
      volumes:
      - name: app
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: my-app
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306
  type: NodePort
